commerce_payment.commerce_payment_gateway.plugin.novalnet_invoice:
  type: commerce_payment_gateway_configuration
  mapping:
    notification:
      type: string
      label: 'Notification for the buyer'
      translatable: true
    upload_logo:
      type: file
      label: 'Upload payment logo'
      translatable: true
    novalnet_invoice_due_date:
      type: string
      label: 'Payment due date (in days)'
      translatable: true
    transaction_type:
      type: string
      label: 'Payment action'
      translatable: true
    manual_amount_limit:
      type: string
      label: 'Minimum transaction limit for authorization'
      translatable: true
    order_completion_status:
      type: string
      label: 'Order completion status'
      translatable: true
    callback_order_status:
      type: string
      label: 'Callback order status'
      translatable: true
    invoice_guarantee_payment:
      type: boolean
      label: 'Enable payment guarantee'
      translatable: true
    invoice_guarantee_payment_minimum_order_amount:
      type: string
      label: 'Minimum order amount (in minimum unit of currency. E.g. enter 100 which is equal to 1.00)'
      translatable: true
    novalnet_invoice_guarantee_payment_pending_status:
      type: string
      label: 'Order status for the pending Guaranteed payment'
      translatable: true
    novalnet_invoice_force_normal_payment:
      type: boolean
      label: 'Force Non-Guarantee payment'
      translatable: true
commerce_payment.commerce_payment_gateway.plugin.novalnet_sepa:
  type: commerce_payment_gateway_configuration
  mapping:
    notification:
      type: string
      label: 'Notification for the buyer'
      translatable: true
    upload_logo:
      type: file
      label: 'Upload payment logo'
      translatable: true
    transaction_type:
      type: string
      label: 'Payment action'
      translatable: true
    manual_amount_limit:
      type: string
      label: 'Minimum transaction limit for authorization'
      translatable: true
    order_completion_status:
      type: string
      label: 'Order completion status'
      translatable: true
    novalnet_sepa_guarantee_payment:
      type: boolean
      label: 'Enable payment guarantee'
      translatable: true
    novalnet_sepa_guarantee_payment_minimum_order_amount:
      type: string
      label: 'Minimum order amount (in minimum unit of currency. E.g. enter 100 which is equal to 1.00)'
      translatable: true
    novalnet_sepa_guarantee_payment_pending_status:
      type: string
      label: 'Order status for the pending Guaranteed payment'
      translatable: true
    novalnet_sepa_force_normal_payment:
      type: boolean
      label: 'Force Non-Guarantee payment'
      translatable: true
commerce_payment.commerce_payment_gateway.plugin.novalnet_prepayment:
  type: commerce_payment_gateway_configuration
  mapping:
    notification:
      type: string
      label: 'Notification for the buyer'
      translatable: true
    upload_logo:
      type: file
      label: 'Upload payment logo'
      translatable: true
    order_completion_status:
      type: string
      label: 'Order completion status'
      translatable: true
    callback_order_status:
      type: string
      label: 'Callback order status'
      translatable: true
commerce_payment.commerce_payment_gateway.plugin.novalnet_cashpayment:
  type: commerce_payment_gateway_configuration
  mapping:
    notification:
      type: string
      label: 'Notification for the buyer'
      translatable: true
    upload_logo:
      type: file
      label: 'Upload payment logo'
      translatable: true 
    slip_expiry_date:
      type: string
      label: 'Slip expiry date (in days)'
      translatable: true
    order_completion_status:
      type: string
      label: 'Order completion status'
      translatable: true
    callback_order_status:
      type: string
      label: 'Callback order status'
      translatable: true
commerce_payment.commerce_payment_gateway.plugin.novalnet_cc:
  type: commerce_payment_gateway_configuration
  mapping:
    notification:
      type: string
      label: 'Notification for the buyer'
      translatable: true
    upload_logo:
      type: file
      label: 'Upload payment logo'
      translatable: true 
    cc_inline_iframe:
      type: boolean
      label: 'Enable Credit Card Inline iframe'
      translatable: true
    order_completion_status:
      type: string
      label: 'Order completion status'
      translatable: true
    transaction_type:
      type: string
      label: 'Payment action'
      translatable: true
    manual_amount_limit:
      type: string
      label: 'Minimum transaction limit for authorization'
      translatable: true
    novalnet_creditcard_css_label:
      type: string
      label: 'Label'
      translatable: true
    novalnet_creditcard_css_input:
      type: string
      label: 'Input'
      translatable: true
    novalnet_creditcard_css_text:
      type: string
      label: 'CSS Text'
      translatable: true
commerce_payment.commerce_payment_gateway.plugin.novalnet_sofort:
  type: commerce_payment_gateway_configuration
  mapping:
    notification:
      type: string
      label: 'Notification for the buyer'
      translatable: true
    upload_logo:
      type: file
      label: 'Upload payment logo'
      translatable: true 
    order_completion_status:
      type: string
      label: 'Order completion status'
      translatable: true
commerce_payment.commerce_payment_gateway.plugin.novalnet_paypal:
  type: commerce_payment_gateway_configuration
  mapping:
    notification:
      type: string
      label: 'Notification for the buyer'
      translatable: true
    upload_logo:
      type: file
      label: 'Upload payment logo'
      translatable: true 
    transaction_type:
      type: string
      label: 'Payment action'
      translatable: true
    manual_amount_limit:
      type: string
      label: 'Minimum transaction limit for authorization'
      translatable: true
    order_completion_status:
      type: string
      label: 'Order completion status'
      translatable: true
    order_pending_status:
      type: string
      label: 'Order status for the pending payment'
      translatable: true
commerce_payment.commerce_payment_gateway.plugin.novalnet_eps:
  type: commerce_payment_gateway_configuration
  mapping:
    notification:
      type: string
      label: 'Notification for the buyer'
      translatable: true
    upload_logo:
      type: file
      label: 'Upload payment logo'
      translatable: true 
    order_completion_status:
      type: string
      label: 'Order completion status'
      translatable: true
commerce_payment.commerce_payment_gateway.plugin.novalnet_ideal:
  type: commerce_payment_gateway_configuration
  mapping:
    notification:
      type: string
      label: 'Notification for the buyer'
      translatable: true
    upload_logo:
      type: file
      label: 'Upload payment logo'
      translatable: true 
    order_completion_status:
      type: string
      label: 'Order completion status'
      translatable: true
commerce_payment.commerce_payment_gateway.plugin.novalnet_giropay:
  type: commerce_payment_gateway_configuration
  mapping:
    notification:
      type: string
      label: 'Notification for the buyer'
      translatable: true
    upload_logo:
      type: file
      label: 'Upload payment logo'
      translatable: true 
    order_completion_status:
      type: string
      label: 'Order completion status'
      translatable: true
commerce_payment.commerce_payment_gateway.plugin.novalnet_przelewy24:
  type: commerce_payment_gateway_configuration
  mapping:
    notification:
      type: string
      label: 'Notification for the buyer'
      translatable: true
    upload_logo:
      type: file
      label: 'Upload payment logo'
      translatable: true 
    order_completion_status:
      type: string
      label: 'Order completion status'
      translatable: true
    order_pending_status:
      type: string
      label: 'Order status for the pending payment'
      translatable: true
